# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RemoteProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'PodPrivate', :git => 'https://github.com/davidecalo/PodPrivate.git'

  # Pods for RemoteProject

end
